name: frontend
description: "A Flutter project for EHR Management & Medicine Tracking."

publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.3.1 <4.0.0"

dependencies:
    cupertino_icons: ^1.0.6
    flutter:
        sdk: flutter
    go_router: ^14.1.4
    google_fonts: ^6.2.1
    http: ^1.2.1
    intl: ^0.19.0
    material_symbols_icons: ^4.2758.0
    provider: ^6.1.2
    url_strategy: ^0.2.0

dev_dependencies:
    flutter_lints: ^4.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
